### ISSUE TITLE
IDE won't fork and submit pull request.

### ISSUE THREAD

**Issue by gruiz016** [learn-co-curriculum/ruby-gets-input#27] opened 2018-10-22 13:56 UTC
Even though lab has passed, i can't fork or submit pull request to move on

**Comment by maxwellbenton** [comment] 2018-10-23 16:23
Thank you for spotting this and providing feedback, @gruiz016.

This issue occurred for multiple students over the past day or so and we believe it was caused by an outage on GitHub (https://www.onmsft.com/news/github-suffers-hours-long-outage-coming-back-online-now). As of now, this lesson is correctly forking and submitting, so I am going to close this issue for now.

If you are still unable to fork and/or submit this lesson, please re-open this issue. 💙

**Closed as completed by maxwellbenton** 2018-10-23 16:23 UTC
Labels: Product
